Library/Controllers/BorrowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Models.Entity;
using Action = Library.Models.Entity.Action;

namespace Library.Controllers
{
    public class BorrowController : Controller
    {
        // GET: Borrow
        DbLibraryEntities db = new DbLibraryEntities();
        [Authorize(Roles ="A")]
        public ActionResult Index()
        {
            var degerler = db.Action.Where(x => x.ProcessStatus == false).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            List<SelectListItem> deger1 = (from x in db.Member.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.MemberName + " " + x.MemberSurname,
                                               Value = x.Id.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from y in db.Book.Where(x=>x.Status== true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.BookName,
                                               Value = y.Id.ToString()
                                           }).ToList();
            List<SelectListItem> deger3 = (from z in db.Staff.ToList()
                                           select new SelectListItem
                                           {
                                               Text = z.Staff1,
                                               Value = z.Id.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(Action p)
        {
            var d1 = db.Member.Where(x => x.Id == p.Member1.Id).FirstOrDefault();
            var d2 = db.Book.Where(y => y.Id == p.Book1.Id).FirstOrDefault();
            var d3 = db.Staff.Where(z => z.Id == p.Staff1.Id).FirstOrDefault();
            p.Member1 = d1;
            p.Book1 = d2;
            p.Staff1 = d3;
            db.Action.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult OduncIade(Action p)
        {
            var odn = db.Action.Find(p.Id);
            DateTime d1 = DateTime.Parse(odn.ReturnDate.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr = d3.TotalDays;

            return View("OduncIade", odn);
        }
        public ActionResult OduncGuncelle(Action p)
        {
            var act = db.Action.Find(p.Id);
            act.MemberDate = p.MemberDate;
            act.ProcessStatus = true;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

    }
}

Library/Views/Borrow/Index.cshtml
@using Library.Models.Entity
@model List<Library.Models.Entity.Action>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<h2>ÖDÜNÇ KİTAP LİSTESİ</h2>



<table class="table table-bordered">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>İşlem ID</th>
        <th>Kitap Adı</th>
        <th>Üye</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
      
    </tr>

    @foreach (var k in Model)
    {
        <tr>
            <td>@k.Id</td>
            <td>@k.Book1.BookName</td>
            <td>@k.Member1.MemberName&nbsp @k.Member1.MemberSurname</td>
            <td>@k.Staff1.Staff1</td>
            <td>@Convert.ToDateTime(k.BorrowDate).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(k.ReturnDate).ToString("dd/MM/yyyy")</td>
         
            <td> <a href="/Borrow/Odunciade/@k.Id" class="btn btn-default"
                    style="background-color:#38d508; color:white">Kitabı İade Et</a></td>
            
        </tr>
    }
</table>

Library/Views/Borrow/OduncIade.cshtml
@model Library.Models.Entity.Action
@{
    ViewBag.Title = "OduncIade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("OduncGuncelle", "Borrow", FormMethod.Post))
{

    <div style="margin-bottom:15px"></div>
    <div class="form-group">

        <label>İşlem ID</label>
        @Html.TextBoxFor(k => k.Id, new { @class = "form-control" })
        <br />

        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.Book1.BookName, new { @class = "form-control" })

        <br />

        <label>Üye</label>
        @Html.TextBoxFor(k => k.Member1.MemberName, new { @class = "form-control" })
        <br />

        <label>Personel</label>
        @Html.TextBoxFor(k => k.Staff1.Staff1, new { @class = "form-control" })

        <br />

        <label>Alış Tarihi</label>
        @Html.TextBoxFor(k => k.BorrowDate, "{0:dd.MM.yyyy}", new { @class = "form-control" })

        <br />

        <label>İade Tarihi</label>
        @Html.TextBoxFor(k => k.ReturnDate, "{0:dd.MM.yyyy}", new { @class = "form-control" })

        <br />

        <label>Üyenin Getirdiği Tarih</label>
        <input type="text" class="form-control" name="MemberDate"
               value="@DateTime.Now.ToShortDateString() " />
    
        <br />
        <label>Geç Gelen Gün Sayısı</label>
        <input type="text" class="form-control" id="Gecinput" value="@ViewBag.dgr" />
    
    </div>
    <div>
        <button class="btn btn-group" style="background-color: #38d508; color: white">Ödünç Kitabı Geri Al</button>
    </div>
}

Library/Views/Borrow/OduncVer.cshtml
@model Library.Models.Entity.Action
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Üye ID</label>
        @*@Html.TextBoxFor(k => k.Member, new { @class = "form-control" })*@
        @Html.DropDownListFor(k=>k.Member1.Id,(List<SelectListItem>)
       ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap ID</label>
        @Html.DropDownListFor(k => k.Book1.Id, (List<SelectListItem>)
      ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Personel ID</label>
        @Html.DropDownListFor(k => k.Staff1.Id, (List<SelectListItem>)
ViewBag.dgr3, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Alış Tarihi </label>
        <input type="text" class="form-control" name="BorrowDate"
               value="@DateTime.Now.ToShortDateString() "/>
    </div>
    <div style="margin-top:15px">
        <label>Kitap İade Tarihi</label>
        <input type="text" class="form-control" name="ReturnDate" value="@DateTime.Now.AddDays(7).ToShortDateString()" />
    </div>



    <div style="margin-top:15px">
        <button class="btn btn-group" style="background-color:#e021e6; color:white">Kitabı Ödünç Ver</button>
        <input type="hidden" value="False" name="ProcessStatus" />
    </div>
</form>