Library/Models/Entity/Announcements.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        public byte Id { get; set; }
        public string Category { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}

Library/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Models.Entity;

namespace Library.Controllers
{
    public class AnnouncementController : Controller
    {
        // GET: Announcement
        DbLibraryEntities db = new DbLibraryEntities();
        public ActionResult Index()
        {
            var degerler = db.Announcements.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniDuyuru()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniDuyuru(Announcements d)
        {
            db.Announcements.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil (int id)
        {
            var duyuru = db.Announcements.Find(id);
            db.Announcements.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(Announcements p)
        {
            var duyuru = db.Announcements.Find(p.Id);
            return View("DuyuruDetay", duyuru);
        }
        public ActionResult DuyuruGüncelle(Announcements t)
        {
            var duyuru = db.Announcements.Find(t.Id);
            duyuru.Category = t.Category;
            duyuru.Contents = t.Contents;
            duyuru.Date = t.Date;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Library/Views/Announcement/DuyuruDetay.cshtml
@model Library.Models.Entity.Announcements
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Announcement", FormMethod.Post))
{

<div style="margin-bottom:15px"></div>
<div class="form-group">

    <label>ID</label>
    @Html.TextBoxFor(k => k.Id, new { @class = "form-control" })
    <br />

    <label>Duyuru Kategori</label>
    @Html.TextBoxFor(k => k.Category, new { @class = "form-control" })
    <br />
    <label>Duyuru İçerik</label>
    @Html.TextAreaFor(k => k.Contents, new { @class = "form-control" })
    <br />
    <label>Duyuru Tarih</label>
    @Html.TextBoxFor(k => k.Date, new { @class = "form-control" })

</div>
<div>
    <button class="btn btn-warning">Güncelle</button>
</div>
}

Library/Views/Announcement/Index.cshtml
@using Library.Models.Entity;
@model List<Announcements>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
   
}

<h2>Duyurular</h2>
<br />

<table class="table table-bordered">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>DUYURU NO</th>
        <th>KATEGORİ</th>
        <th>TARİH</th>
        <th>SİL</th>
        <th>İÇERİK</th>
    </tr>

    @foreach (var prs in Model)
    {
       

<tr>
    <td>@prs.Id</td> @*prs den gelen Id adı *@
    <td>@prs.Category</td>
    <td>@Convert.ToDateTime(prs.Date).ToString("dd/MM/yyyy")</td>
    <td><a href="/Announcement/DuyuruSil/@prs.Id" class="btn btn-danger">Sil</a></td>
    <td><a href="/Announcement/DuyuruDetay/@prs.Id" class="btn btn-default" style="background-color:skyblue">Detaylar</a></td>
</tr>
    }
</table>

<a href="/Announcement/YeniDuyuru/" class="btn btn-primary">Yeni Duyuru Ekle</a>

Library/Views/Announcement/YeniDuyuru.cshtml
@model Library.Models.Entity.Announcements
@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>YeniDuyuru</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>

        @Html.TextBoxFor(x => x.Category, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçeriği</label>

        @Html.TextBoxFor(x => x.Contents, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarih</label>

        @Html.TextBoxFor(x => x.Date, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Ekle</button>
    </div>


</form>