Library/Controllers/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Library.Models.Entity;

namespace Library.Controllers
{
    [AllowAnonymous]
    public class AdminLoginController : Controller
    {
       
        // GET: AdminLogin
        DbLibraryEntities db = new DbLibraryEntities();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Admin p)
        {
            var bilgiler = db.Admin.FirstOrDefault(x=>x.AdminUser == p.AdminUser &&
            x.Password==p.Password);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.AdminUser, false);
                Session["AdminUser"] = bilgiler.AdminUser.ToString();
                return RedirectToAction("Index", "Category");
            }
            else
            {
                return View(bilgiler);
            }

           
        }
    }
}

Library/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Models.Entity;
using System.Web.Security;

namespace Library.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        // GET: Login
        DbLibraryEntities db = new DbLibraryEntities();
        public ActionResult GirisYap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GirisYap(Member p)
        {
            var bilgiler = db.Member.FirstOrDefault(x => x.Email == p.Email &&
            x.Password == p.Password);
            if(bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.Email, false);
                Session["Mail"] = bilgiler.Email.ToString();
                
                return RedirectToAction("Index", "Panel");
            }
            else
            {
                return View();
            }
            
        }

    }
}

Library/Views/AdminLogin/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Log in (v2)</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-master/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/AdminLTE-master/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-master/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        @using (Html.BeginForm("Login", "AdminLogin", FormMethod.Post))
        {


            <div class="card card-outline card-primary">
                <div class="card-header text-center">
                    <a href="~/AdminLTE-master/index2.html" class="h1"><b>Admin</b>Giriş</a>
                </div>
                <div class="card-body">
                    <p class="login-box-msg">Oturum Aç</p>

                    <form action="../../index3.html" method="post">
                        <div class="input-group mb-3">
                            <input type="email" name="AdminUser" class="form-control" placeholder="Mail">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" name="Password" class="form-control" placeholder="Şifre">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-8">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="remember">
                                    <label for="remember">
                                        Beni Hatırla
                                    </label>
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">Giriş</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>

                    <div class="social-auth-links text-center mt-2 mb-3">
                        <p>- VEYA - </p>
                        <a href="#" class="btn btn-block btn-primary">
                            <i class="fab fa-facebook mr-2"></i> Facebook'la Bağlan
                        </a>
                        <a href="#" class="btn btn-block btn-danger">
                            <i class="fab fa-google-plus mr-2"></i> Google+ ile Bağlan
                        </a>
                    </div>
                    <!-- /.social-auth-links -->

                    <p class="mb-1">
                        <a href="forgot-password.html">Şifremi Unuttum</a>
                    </p>
                    <p class="mb-0">
                        <a href="/Window/Index/" class="text-center">Vtirine Geri Dön</a>
                    </p>
                </div>
                <!-- /.card-body -->
            </div>
        }
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/AdminLTE-master/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-master/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-master/dist/js/adminlte.min.js"></script>
</body>
</html>